### ISSUE TITLE
Better UnspentXP tracking

### ISSUE THREAD

**Issue by geoidesic** [geoidesic/surge#52]
1. [ ] unspentXp should only allow digits 
2. [ ] Probably it should require confirmation to edit that field 
3. [ ] and ideally there should be a history of changes stored against the character
